// rcc.c, Michael Haselberger
// Description: This file implements functions to configure the system and peripheral clocks.

// Clock configurated with the help of STM RCC clock config example code:
// https://github.com/STMicroelectronics/STM32CubeH7/tree/master/Projects/NUCLEO-H745ZI-Q/Examples/RCC/RCC_ClockConfighttps://github.com/STMicroelectronics/STM32CubeH7/tree/master/Projects/NUCLEO-H745ZI-Q/Examples/RCC/RCC_ClockConfig
// Code generated by STM32CubeMX had multiple errors and leaves a lot to be desired in general.
#include "rcc.h"

/*
 *	System Clock is configured as follows : 
 *            System Clock source            = PLL (HSE BYPASS)
 *            SYSCLK(Hz)                     = 480 MHz (CPU Clock)
 *            HCLK(Hz)                       = 240 MHz (Cortex-M4 CPU, Bus matrix Clocks)
 *            AHB Prescaler                  = 2
 *            D1 APB3 Prescaler              = 2 (APB3 Clock  120 MHz)
 *            D2 APB1 Prescaler              = 2 (APB1 Clock  120 MHz)
 *            D2 APB2 Prescaler              = 2 (APB2 Clock  120 MHz)
 *            D3 APB4 Prescaler              = 2 (APB4 Clock  120 MHz)
 *            HSE Frequency(Hz)              = 8 MHz
 *            PLL_M                          = 1
 *            PLL_N                          = 120
 *            PLL_P                          = 2	// 8 MHz (HSE) / 1 (PLL_M) * 120(PLL_N) / 2(PLL_P) = 480 MHz PLLCLK -> SYSCLK
 *            PLL_Q                          = 4	
 *            PLL_R                          = 2	 
 *            VDD(V)                         = 3.3
 *            Flash Latency(WS)              = 4
*/

void SystemClock_Config(void)
{
	RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
	RCC_OscInitTypeDef RCC_OscInitStruct = {0};
	HAL_StatusTypeDef ret = HAL_OK;

	// enable supply configuration update
	HAL_PWREx_ConfigSupply(PWR_DIRECT_SMPS_SUPPLY);

	/* 
        The voltage scaling allows optimizing the power consumption when the device is
        clocked below the maximum system frequency, to update the voltage scaling value
        regarding system frequency refer to product datasheet.  
    */

	// --------- 480 MHz/240 MHz core clocks and SPI/I2S Clock optimized for 48kHz
	// set voltage scaling to 0, because the clock is running at maximum 480 MHz
	// "Run Mode Range 0: enhanced performnance with high power consumption"
	// might look into reconfiguring mcu to use voltage scale 1(max 400 MHz) once at the optimizing stage.
	// for now, battery life (or even battery supplied usage) is not a pressing concern/priority.
	__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE0);
	// wait until ready
	while (!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY))
	{
	}

	// Macro to configure the PLL clock source as high speed external
	//__HAL_RCC_PLL_PLLSOURCE_CONFIG(RCC_PLLSOURCE_HSE);

	// initialize RCC oscillator - turn on HSE only, HSI and CSI off
	RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
	RCC_OscInitStruct.HSEState = RCC_HSE_ON;
	RCC_OscInitStruct.HSIState = RCC_HSI_OFF;
	RCC_OscInitStruct.CSIState = RCC_CSI_OFF;
	RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
	RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;

	RCC_OscInitStruct.PLL.PLLM = 2;
	RCC_OscInitStruct.PLL.PLLN = 120;
	RCC_OscInitStruct.PLL.PLLFRACN = 0;
	RCC_OscInitStruct.PLL.PLLP = 2;
	RCC_OscInitStruct.PLL.PLLQ = 4;
	RCC_OscInitStruct.PLL.PLLR = 2;

	RCC_OscInitStruct.PLL.PLLRGE = RCC_PLL1VCIRANGE_3;
	RCC_OscInitStruct.PLL.PLLVCOSEL = RCC_PLL1VCOWIDE;
	RCC_OscInitStruct.PLL.PLLFRACN = 0;

	// check oscillator setup for errors
	ret = HAL_RCC_OscConfig(&RCC_OscInitStruct);
	if (ret != HAL_OK)
	{
		Error_Handler();
	}

	// Select PLL as system clock source and configure bus clock dividers
	RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2 | RCC_CLOCKTYPE_D3PCLK1 | RCC_CLOCKTYPE_D1PCLK1;

	RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
	RCC_ClkInitStruct.SYSCLKDivider = RCC_SYSCLK_DIV1;
	RCC_ClkInitStruct.AHBCLKDivider = RCC_HCLK_DIV2;
	RCC_ClkInitStruct.APB3CLKDivider = RCC_APB3_DIV2;
	RCC_ClkInitStruct.APB1CLKDivider = RCC_APB1_DIV2;
	RCC_ClkInitStruct.APB2CLKDivider = RCC_APB2_DIV2;
	RCC_ClkInitStruct.APB4CLKDivider = RCC_APB4_DIV2;

	ret = HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4);
	if (ret != HAL_OK)
	{
		Error_Handler();
	}
}

/*
 *  Recommended I2S MCLK/LRCK ratios for a sampling rate Fs = 48 KHz (Single-Speed Mode) are 256x, 384x, 512x, 768x or 1024x.
 *  => PMOD I2S2 Codec Reference Manual
 *  Codec is running in slave mode, so clocks have to be generated/provided by uC.
 *  
 *	The frequency generated on MCK, CK and WS depends mainly on the I2SDIV, ODD, CHLEN and MCKOE bits in the SPI/I2S configuration 
 *	register SPI_I2SCFGR (Reference Manual 53.11.13)
 *		MCKOE:		  master clock output enable
 *		ODD:		  odd factor for the prescaler 
 *							0: real divider value = I2SDIV * 2
 *							1: real divider value = (I2SDIV * 2) + 1
 *		ISDIV[7:0]:	  I2S linear prescaler. Can take any value except the value 1, when ODD is alos equal to 1.
 *		CHLEN:		  Channel length (number of bits per audio channel)
 *							0: 16 bit wide
 *							1: 32 bit wide
 *							
 *	Section 53.9.9: Clock generator:
 *		Formulas for frequency of frame synchronization (F_WS) and master clock (F_MCK)
 *					  F_WS = F_I2SCLK / (256 * {(2 * I2SDIV) + ODD}
 *					  F_MCK = F_WS * 256
 *		where F_I2SCLK is the frequency of the kernel clock provided to the SPI/I2S block, F_WS is the Word Select Clock ( = Fs)
 *		frequency and F_MCK is the Master Clock frequency generated by the I2S Master.
 *		
 *					  F_WS = Fs = 48 KHz		  
 *					  
 *					  => F_MCK = 48 KHz * 256 = 12.288 MHz ( = "magic audio frequency")
 *					  Using an external oscillator with this value would be ideal here. 
 *					  Since no such crystal is available to me, the PLL to the I2S block has been divided down to 12.336 MHz, which
 *					  yields a FS of 47.9 KHz, +- 100 Hz (0.01% precision).
 *	    see https://github.com/cnoviello/mastering-stm32/blob/master/nucleo-l053R8/system/src/stm32l0xx/stm32l0xx_hal_i2s.c
 *					  
 *					  
 *	M = 7			// Division factor for PLL VCO input clock
 *	N = 172			// Multiplication factor for PLL VCO output clock
 *	P = 4			// Division factor for system clock
 *		
 *	Common peripheral clock for SPI/I2S is configured as follows (PLL2): 
 *            HSE Frequency(Hz)              = 8 MHz
 *            PLL_M                          = 4
 *            PLL_N                          = 172
 *            PLL_P                          = 7	
 *            
 *			  => 8 MHz (HSE) / 7 (PLL_M) * 172(PLL_N) / 4(PLL_P) = 49.14286 MHz = approx 4 * F_MCK
*/

void PeriphCommonClock_Config(void)
{
	RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};

	// Enable peripheral clock for SPI1 and SPI2
//	PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_SAI1 | RCC_PERIPHCLK_SPI2;
	PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_SPI2;
	PeriphClkInitStruct.PLL2.PLL2M = 7;
	PeriphClkInitStruct.PLL2.PLL2N = 172;
	PeriphClkInitStruct.PLL2.PLL2P = 4;
	PeriphClkInitStruct.PLL2.PLL2Q = 2;
	PeriphClkInitStruct.PLL2.PLL2R = 2;
	PeriphClkInitStruct.PLL2.PLL2RGE = RCC_PLL2VCIRANGE_0;
	PeriphClkInitStruct.PLL2.PLL2VCOSEL = RCC_PLL2VCOWIDE;
	PeriphClkInitStruct.PLL2.PLL2FRACN = 0;
	//PeriphClkInitStruct.Sai1ClockSelection = RCC_SAI1CLKSOURCE_PLL2;
	PeriphClkInitStruct.Spi123ClockSelection = RCC_SPI123CLKSOURCE_PLL2;

	if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
	{
		Error_Handler();
	}
}